# Generated by Django 3.2.6 on 2021-11-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
