# Generated by Django 3.2.6 on 2021-10-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseradiologyservice',
            name='clinical_info',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
