# Generated by Django 3.2.6 on 2021-10-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiology', '0002_raiseradiologyservice_clinical_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaiseRadiologyService',
            new_name='RadiologyRequest',
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.PositiveIntegerField(default=1)),
                ('diagnosis', models.CharField(blank=True, max_length=225, null=True)),
                ('other_findings', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radiologyrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyrequest')),
            ],
        ),
    ]
