# Generated by Django 3.2.6 on 2021-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_auto_20211015_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyreport',
            name='findings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='other_findings',
            field=models.TextField(),
        ),
    ]
