# Generated by Django 3.2.6 on 2021-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_auto_20211015_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='decline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
