# Generated by Django 3.2.6 on 2021-11-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_auto_20211015_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
