# Generated by Django 3.2.6 on 2021-11-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_radiologyrequest_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyrequest',
            old_name='radiology_service',
            new_name='radiology_request',
        ),
    ]
