# Generated by Django 3.2.6 on 2021-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
